version: '3.9'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      MSSQL_SA_PASSWORD: "SecretPassword"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
        - ./data/data:/var/opt/mssql/data
        - ./data/log:/var/opt/mssql/log
        - ./data/secrets:/var/opt/mssql/secrets